version: '3.8'
services:
  db:
    container_name: ${POSTGRES_DB_CONTAINER_NAME}
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  # michael-shop:
  #   image: michael-shop-app:0.0.1
  #   container_name: michael-shop-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: prod
  #   ports:
  #     - 3001:${PORT}
  #   environment:
  #     - POSTGRES_DB_HOST=${POSTGRES_DB_CONTAINER_NAME}
  #     - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
  #     - POSTGRES_DB_USER=${POSTGRES_DB_USER}
  #     - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
  #     - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
  #     - PORT=${PORT}
  #   depends_on:
  #     - db
  #   volumes:
  #     - node_modules:/app/node_modules
  #   restart: always

volumes:
  # node_modules: {
  #   external: false
  # }
  postgres: {
    external: false
  }

